name: Test-OpenPlanner
on: [push]
jobs:
  Test-OpenPlanner:
    runs-on: [self-hosted, linux]
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job's status is ${{ job.status }}."
      - run: echo "github hash  ${{ github.sha }}_common"
      - run: |
          cd /home/hil/ros_ci_docker/
          rm ci-test.repos
          echo "repositories:
            common:
              type: git
              url: https://github.com/MathiasPechinger/common_2.git
              version: ${{ github.ref_name }}
            core_perception:
              type: git
              url: https://github.com/MathiasPechinger/core_perception.git
              version: openplanner.1.15
            core_planning:
              type: git
              url: https://github.com/MathiasPechinger/core_planning.git
              version: openplanner.1.15
            messages:
              type: git
              url: https://github.com/MathiasPechinger/messages.git
              version: master
            visualization:
              type: git
              url: https://github.com/MathiasPechinger/visualization.git
              version: dev-op.1.15-advancements" >> ci-test.repos
        
      - run: |
          cd /home/hil/ros_ci_docker/
          docker run --mount type=bind,source="$(pwd)"/,target=/app -p 8080:90 ci/ros:scenario_sim
          mv /home/hil/ros_ci_docker/results/new_results /home/hil/ros_ci_docker/results/${{ github.sha }}_common